name: Run ESLint
on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '14.x'
      - run: npm install
      - run: git fetch --depth=1 origin ${{ github.base_ref }}
      - run: git diff remotes/origin/${{ github.base_ref }} --name-only --diff-filter=ACM | grep -E '\.[tj]s$' | xargs npx eslint
